---
# Source: simetrik/templates/server/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: server
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: server
